using Booking.Domain.DbContexts;
using Booking.Domain.Model;
using System.Linq;

namespace Booking.Domain.Seed.Builders
{
	class UserProfileBuilder : DataSeedBuilderBase, IDataSeedBuilder
	{

		public UserProfileBuilder(BookingDbContext context)
			: base(context)
		{
		}

		protected override void Create()
		{
			if (!Context.UserProfiles.Any())
			{
				var user = new UserProfile()
				{
					FirstName = "Admin",
					LastName = "Admin",
					Email = "admin@admin.com",
					UserName = "admin",
					NormalizedUserName = "ADMIN",
					PhoneNumber = "123",
					Notification = "First user generated by app"
				};

				Context.UserProfiles.Add(user);
				Context.SaveChanges();
			}
		}
	}
}
